### PR TITLE
Correction of Image.php to solve error when saving posts without images

### PR DESCRIPTION
**Pull request by espressobytes**
Fix of issue #203: Saving Post with no image fails

### Description
When saving a new blog without image, an Exception is thrown: The file was not uploaded
Preconditions and steps to reproduce are better explained [here](https://github.com/mageplaza/magento-2-blog/issues/203).

### Fixed Issues (if relevant)
https://github.com/mageplaza/magento-2-blog/issues/203: Issue title

### Manual testing scenarios

1. Install Mageplaza Blog Extension via composer
2. Activate Extension in Magento-Configuration
3. In Magento-Admin Navigate to Content -> Manage Posts
4. Click on Add New Post
5. Type in Title, Description and some content but upload no image
6. Click on Save

### CODE REVIEW

**Comment by NgoDuVietHung97** [comment]
Hi @espressobytes,

Thanks for your contribution.
We will update this in the repo and we will release the new version soon.
Thank you very much!

**Comment by OvalMedia** [comment]
This has been reported multiple times. I even suggested a solution (in the core module though): https://github.com/mageplaza/magento-2-blog/issues/189#issuecomment-496829489

This has NOT been fixed in the latest 3.0.6. You need to fix the CORE module.

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

We are considering updating this in module-core or in the Blog Extension.
We will update and release the new version as soon as possible, so please look forward to this.
Thanks for your understanding!

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

We are considered the problem and we have found a  better solution to this problem.
We have updated on branch "develop", you can check it at commit https://github.com/mageplaza/magento-2-blog/commit/97d4798b4c481c54f6df5798572b7cba6a0a7546
If you have any other question, please let me know.
Thank you!

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

We have found a better solution for this issue, you can check at commit https://github.com/mageplaza/magento-2-blog/commit/684fb37d849de752f886aafbbdfeedb10f26f812
This error is caused by the blog module, so we just need to update in blog extension.
We will update it in the next version and we will release the new version soon.
Thank you very much!

**Comment by mrk-dzie** [comment]
Is it fixed already?

**Comment by mashasauer** [comment]
This is also happening when saving/updating Authors info without adding an image.

**Comment by NgoDuVietHung97** [comment]
Hi @mashasauer,

Thanks for your feedback.
We will update this soon, so please look forward to this.

Thanks!

**Comment by thaimageplaza** [comment]
Thanks for your contributions! 
Your feedback helps us improve our extension and help troubleshoot for you and other customers. So I really appreciate you taking the time here. More importantly, we will surely release the function in the upcoming version.

Since there is no issue left, I want to reach out and let you know we are going to close this pull.
Please don’t hesitate to contact me if ever a problem should arise. We hope to have the pleasure of doing business with you for many years to come.

**Pull request closed without merging**
