### PR TITLE
Fix blog items with multiple stores

### PR DESCRIPTION
**Pull request by Basvkempen1**

### CODE REVIEW

**Comment by Basvkempen1** [comment]
Can this Pr be checked?
One of our customers desperetly needs this change

Thanks !

**Comment by thaimageplaza** [comment]
Thank you very much for your feedback.
I have updated it in develop branch. Please check again.
Thank you!
https://github.com/mageplaza/magento-2-blog/commit/cfec4e19aa80551686a7ae43f36691afe3e58b78

**Comment by Basvkempen1** [comment]
Cool, when wil lthis be released to the master branch?

**Comment by Basvkempen1** [comment]
@thaimageplaza 
Any ETA when this will be release to the master branch?

**Comment by Basvkempen1** [comment]
Do you have any ETA when there will be an release with this fix ?

**Comment by Basvkempen1** [comment]
Hello? Is there any chance I can get update on this ?

**Comment by NgoDuVietHung97** [comment]
Hi @Basvkempen1,

Sorry for the late reply. We have no plans to update now.
However, I will surely note it to our developer to consider developing it in the future so please look forward to this.

Thank you!

**Comment by Basvkempen1** [comment]
Hi @NgoDuVietHung97 

Thanks for the update.
You mean you wont be updating and supporting this module anymore whatsoever ?

In that case we might be forced to copy the module to our own repo and keep it maintained ourself.
I clear statement about your priorities regarding the support on this module would be highly appreciated.

Thanks ! :D

**Comment by NgoDuVietHung97** [comment]
Hi @Basvkempen1,

Looks like you misunderstood our idea.
We will update it in the next 1-2 weeks.
Thank you for your understanding!

**Comment by Basvkempen1** [comment]
Ok nice.

Thanks for the clarification!

**Pull request closed without merging**
